name: Feature request
description: Request a new feature for the Package
title: "[Feature]: "
labels: ["feature"]
body:
    - type: textarea
      id: new-feature
      attributes:
          label: What feature would you like to see added?
          placeholder: I would like to see X feature added to the package.
      validations:
          required: true
